global:
  scrape_interval: 15s
scrape_configs:
  - job_name: flight-ingestion
    metrics_path: /metrics
    static_configs:
      - targets: ['flight-ingestion:8000']
  - job_name: flight-analytics
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['flight-analytics:8080']
