spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/aerostream
    username: aerostream
    password: aerostream
  jpa:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: mongodb://mongo:27017/aerostream
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: flight-analytics
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
