apiVersion: v1
kind: Secret
metadata:
  name: aerostream-secrets
  namespace: aerostream
type: Opaque
stringData:
  AVIATIONSTACK_API_KEY: replace-me
  JWT_SECRET: replace-me
  POSTGRES_PASSWORD: aerostream
